In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
sns.set()
import sklearn
import warnings
warnings.filterwarnings("ignore") #REMOVES ANNOYING WARNINGS

In [2]:
pd.set_option('display.max_columns', None) #VIEW ALL COLUMNS BECAUSE SOME ARE HIDDEN BY DEFAULT

In [3]:
df_summer = pd.read_csv("summer.csv")

In [4]:
df_summer.head()

Year    City     Sport Discipline             Athlete Country Gender  \
0  1896  Athens  Aquatics   Swimming       HAJOS, Alfred     HUN    Men   
1  1896  Athens  Aquatics   Swimming    HERSCHMANN, Otto     AUT    Men   
2  1896  Athens  Aquatics   Swimming   DRIVAS, Dimitrios     GRE    Men   
3  1896  Athens  Aquatics   Swimming  MALOKINIS, Ioannis     GRE    Men   
4  1896  Athens  Aquatics   Swimming  CHASAPIS, Spiridon     GRE    Men   

                        Event   Medal  
0              100M Freestyle    Gold  
1              100M Freestyle  Silver  
2  100M Freestyle For Sailors  Bronze  
3  100M Freestyle For Sailors    Gold  
4  100M Freestyle For Sailors  Silver

In [5]:
df_summer["season"] = "summer" #adding a season column

In [6]:
df_summer.head()

Year    City     Sport Discipline             Athlete Country Gender  \
0  1896  Athens  Aquatics   Swimming       HAJOS, Alfred     HUN    Men   
1  1896  Athens  Aquatics   Swimming    HERSCHMANN, Otto     AUT    Men   
2  1896  Athens  Aquatics   Swimming   DRIVAS, Dimitrios     GRE    Men   
3  1896  Athens  Aquatics   Swimming  MALOKINIS, Ioannis     GRE    Men   
4  1896  Athens  Aquatics   Swimming  CHASAPIS, Spiridon     GRE    Men   

                        Event   Medal  season  
0              100M Freestyle    Gold  summer  
1              100M Freestyle  Silver  summer  
2  100M Freestyle For Sailors  Bronze  summer  
3  100M Freestyle For Sailors    Gold  summer  
4  100M Freestyle For Sailors  Silver  summer

In [7]:
df_winter = pd.read_csv("winter.csv")

In [8]:
df_winter["season"] = "winter" #adding a season column

In [9]:
df_winter.head()

Year      City     Sport Discipline               Athlete Country Gender  \
0  1924  Chamonix  Biathlon   Biathlon           BERTHET, G.     FRA    Men   
1  1924  Chamonix  Biathlon   Biathlon        MANDRILLON, C.     FRA    Men   
2  1924  Chamonix  Biathlon   Biathlon   MANDRILLON, Maurice     FRA    Men   
3  1924  Chamonix  Biathlon   Biathlon       VANDELLE, André     FRA    Men   
4  1924  Chamonix  Biathlon   Biathlon  AUFDENBLATTEN, Adolf     SUI    Men   

             Event   Medal  season  
0  Military Patrol  Bronze  winter  
1  Military Patrol  Bronze  winter  
2  Military Patrol  Bronze  winter  
3  Military Patrol  Bronze  winter  
4  Military Patrol    Gold  winter

In [12]:
df_total = df_summer.append(df_winter,ignore_index=True)""""Merging the two datasets, winter and summer with the 
season column as a new feature"""

In [13]:
df_total.dropna(inplace=True)

In [14]:
df_total.head()

Year    City     Sport Discipline             Athlete Country Gender  \
0  1896  Athens  Aquatics   Swimming       HAJOS, Alfred     HUN    Men   
1  1896  Athens  Aquatics   Swimming    HERSCHMANN, Otto     AUT    Men   
2  1896  Athens  Aquatics   Swimming   DRIVAS, Dimitrios     GRE    Men   
3  1896  Athens  Aquatics   Swimming  MALOKINIS, Ioannis     GRE    Men   
4  1896  Athens  Aquatics   Swimming  CHASAPIS, Spiridon     GRE    Men   

                        Event   Medal  season  
0              100M Freestyle    Gold  summer  
1              100M Freestyle  Silver  summer  
2  100M Freestyle For Sailors  Bronze  summer  
3  100M Freestyle For Sailors    Gold  summer  
4  100M Freestyle For Sailors  Silver  summer

In [15]:
x=df_total.drop(["Medal"],axis=1) #separating the dependent and independent variable columns

In [16]:
x.isnull().sum()

Year          0
City          0
Sport         0
Discipline    0
Athlete       0
Country       0
Gender        0
Event         0
season        0
dtype: int64

In [17]:
from sklearn.preprocessing import LabelEncoder

In [18]:
lb=LabelEncoder()

In [19]:
for col in x.columns:
    x[col] = lb.fit_transform(x[col])#transforming all the categorical to numerical data

In [20]:
x

Year  City  Sport  Discipline  Athlete  Country  Gender  Event  season
0         0     3      0          62     8539       58       0     79       0
1         0     3      0          62     9245        7       0     79       0
2         0     3      0          62     5572       52       0     80       0
3         0     3      0          62    14482       52       0     80       0
4         0     3      0          62     3658       52       0     80       0
...     ...   ...    ...         ...      ...      ...     ...    ...     ...
36930    32    32     37          59    10710       47       1    654       1
36931    32    32     37          59      523      140       1    654       1
36932    32    32     37          59    14488       21       1    655       1
36933    32    32     37          59    20276       31       1    655       1
36934    32    32     37          59    23676       44       1    655       1

[36931 rows x 9 columns]

In [21]:
lb2 = LabelEncoder()

In [22]:
y_clean = lb2.fit_transform(df_total.iloc[:,-2])

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
x_train,x_test,y_train,y_test = train_test_split(x,y_clean,test_size=0.2,random_state =42)

In [25]:
from sklearn.metrics import confusion_matrix # TOOLS TO CHECK ACCURACY
from sklearn import metrics

NOW LET'S TRY DIFFERENT ALGORITHMS THAT SUPPORT MULTICLASS CLASSIFICATION

LOGISTIC REGRESSION

In [26]:
from sklearn.linear_model import LogisticRegression

In [27]:
classifier_log = LogisticRegression(random_state =0,max_iter =200)

In [28]:
classifier_log.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=200, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [29]:
y_pred_log = classifier_log.predict(x_test)

In [30]:
confusion_matrix(y_test,y_pred_log)

array([[ 974, 1084,  373],
       [ 850, 1227,  413],
       [ 952, 1144,  370]], dtype=int64)

In [31]:
metrics.f1_score(y_test,y_pred_log,average="macro")

0.3304008790968018

K NEIGHBORS CLASSIFIER

In [32]:
from sklearn.neighbors import KNeighborsClassifier

In [33]:
classifier_KNN = KNeighborsClassifier()

In [34]:
classifier_KNN.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [35]:
y_pred_KNN = classifier_KNN.predict(x_test)

In [36]:
confusion_matrix(y_test,y_pred_KNN)

array([[1121,  757,  553],
       [ 969, 1035,  486],
       [1084,  767,  615]], dtype=int64)

True positives are the values on the diagonal

In [37]:
metrics.f1_score(y_test,y_pred_KNN,average="macro") # THE CLOSER THE F1 SCORE TO 1, THE MORE SIGNIFICANT THE MODEL

0.3695086213361485

NAIVE BAYES CLASSIFIER

In [38]:
from sklearn.naive_bayes import GaussianNB

In [39]:
classifier_naive = GaussianNB(var_smoothing=1e-09)

In [40]:
classifier_naive.fit(x_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [41]:
y_pred_naive = classifier_naive.predict(x_test)

In [42]:
confusion_matrix(y_test,y_pred_naive)

array([[1141,  940,  350],
       [1014, 1099,  377],
       [1124,  991,  351]], dtype=int64)

In [43]:
metrics.f1_score(y_test,y_pred_naive,average="macro")

0.3319731357361436

DECISION TREE CLASSIFIER

In [46]:
from sklearn.tree import DecisionTreeClassifier

In [47]:
classifier_dectree = DecisionTreeClassifier(criterion = "entropy",random_state =0)

In [48]:
classifier_dectree.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [49]:
y_pred_dectree = classifier_dectree.predict(x_test)

In [50]:
confusion_matrix(y_test,y_pred_dectree)

array([[1659,  373,  399],
       [ 376, 1696,  418],
       [ 406,  436, 1624]], dtype=int64)

In [51]:
metrics.f1_score(y_test,y_pred_dectree,average="macro")

0.6740083722530801

RANDOM FOREST CLASSIFIER

In [52]:
from sklearn.ensemble import RandomForestClassifier

In [121]:
classifier_forest = RandomForestClassifier(criterion="gini",max_depth=None, max_features= 'log2',min_samples_leaf= 1, min_samples_split= 2,n_estimators=500, warm_start = True)

In [122]:
classifier_forest.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='log2', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=500, n_jobs=None,
            oob_score=False, random_state=None, verbose=0, warm_start=True)

In [123]:
y_pred_forest = classifier_forest.predict(x_test)

In [124]:
random_forest_score = metrics.f1_score(y_test,y_pred_forest,average="macro")
random_forest_score

0.6917319597645868

In [103]:
confusion_matrix(y_test,y_pred_forest)

array([[1723,  337,  371],
       [ 373, 1786,  331],
       [ 433,  431, 1602]], dtype=int64)

GRADIENT BOOSTING CLASSIFIER

In [182]:
from sklearn.ensemble import GradientBoostingClassifier

In [183]:
classifier_GBC = GradientBoostingClassifier(random_state=2)
classifier_GBC.fit(x_train,y_train)
y_pred_GBC = classifier_GBC.predict(x_test)

In [184]:
metrics.f1_score(y_test,y_pred_GBC,average="macro")

0.4284019646494434

In [185]:
metrics.confusion_matrix(y_test,y_pred_GBC)

array([[1180,  684,  567],
       [ 789, 1234,  467],
       [ 932,  754,  780]], dtype=int64)

XGB CLASSIFIER

In [186]:
from xgboost import XGBClassifier

In [187]:
classifier_XGB = XGBClassifier(random_state =3)
classifier_XGB.fit(x_train,y_train)
y_pred_XGB = classifier_XGB.predict(x_test)

[12:41:07] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


In [188]:
metrics.f1_score(y_test,y_pred_XGB,average="macro")

0.5582116758569757

In [189]:
metrics.confusion_matrix(y_test,y_pred_XGB)

array([[1404,  500,  527],
       [ 483, 1552,  455],
       [ 658,  628, 1180]], dtype=int64)

BAGGING CLASSIFIER

In [66]:
from sklearn.ensemble import BaggingClassifier

In [69]:
classifier_BC = BaggingClassifier(random_state =3,n_estimators=100,warm_start =True)
classifier_BC.fit(x_train,y_train)
y_pred_BC = classifier_BC.predict(x_test)

In [95]:
bagging_classifier_score =metrics.f1_score(y_test,y_pred_BC,average="macro")
bagging_classifier_score

0.7025051613144736

In [193]:
metrics.confusion_matrix(y_test,y_pred_BC)

array([[1756,  322,  353],
       [ 361, 1788,  341],
       [ 411,  408, 1647]], dtype=int64)

EXTRA TREE CLASSIFIER

In [194]:
from sklearn.tree import ExtraTreeClassifier

In [195]:
classifier_ETC = ExtraTreeClassifier(random_state =3)
classifier_ETC.fit(x_train,y_train)
y_pred_ETC = classifier_ETC.predict(x_test)

In [196]:
metrics.f1_score(y_test,y_pred_ETC,average="macro")

0.6004212624802562

In [197]:
metrics.confusion_matrix(y_test,y_pred_ETC)

array([[1452,  465,  514],
       [ 446, 1515,  529],
       [ 474,  524, 1468]], dtype=int64)

LET'S OPTIMIZE DECISION TREE

In [77]:
from sklearn.model_selection import GridSearchCV

In [75]:
classifier_dtree_grid = DecisionTreeClassifier()

In [78]:
parameters_dtree = [{"max_depth" : [None,1,2,5,7,9],"min_samples_leaf":[1,2,4],"min_samples_split":[2,4,6,8]}]

grid_search_dtree = GridSearchCV(estimator = classifier_dtree_grid ,param_grid = parameters_dtree, n_jobs=-1,cv=10)

In [80]:
grid_search_dtree = grid_search_dtree.fit(x_train,y_train)

In [81]:
y_pred_tree_grid = grid_search_dtree.predict(x_test)

In [82]:
metrics.f1_score(y_test,y_pred_tree_grid,average="macro")

0.6805966979494639

In [84]:
grid_search_dtree.best_params_

{'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 2}

NOW LET'S IMPLEMENT IN THE MODEL

In [85]:
classifier_dtree_grid_best = DecisionTreeClassifier(max_depth = None, min_samples_leaf= 1, min_samples_split= 2)

In [87]:
classifier_dtree_grid_best.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [88]:
y_pred_tree_grid_best = classifier_dtree_grid_best.predict(x_test)

In [94]:
decision_tree_score = metrics.f1_score(y_test,y_pred_tree_grid_best,average="macro")
decision_tree_score

0.6826968800798948

In [ ]:
SO FAR...OUR BEST MODELS WERE DERIVED WITH RANDOM FOREST, DECISION TREE AND BAGGING CLASSIFIER 

In [101]:
classifier_df = pd.DataFrame(data = np.array([bagging_classifier_score,random_forest_score,decision_tree_score]),columns = ["F1-Scores(Macro)"],index=["Bagging Classifier","Random_Forest","Decision Tree"])

In [102]:
classifier_df

F1-Scores(Macro)
Bagging Classifier          0.702505
Random_Forest               0.691541
Decision Tree               0.682697