In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
sns.set()
import sklearn
import warnings
warnings.filterwarnings("ignore") #REMOVES ANNOYING WARNINGS

In [4]:
pd.set_option('display.max_columns', None) #VIEW ALL COLUMNS BECAUSE SOME ARE HIDDEN BY DEFAULT

In [5]:
df_summer = pd.read_csv("summer.csv")

In [6]:
df_summer.head()

Year    City     Sport Discipline             Athlete Country Gender  \
0  1896  Athens  Aquatics   Swimming       HAJOS, Alfred     HUN    Men   
1  1896  Athens  Aquatics   Swimming    HERSCHMANN, Otto     AUT    Men   
2  1896  Athens  Aquatics   Swimming   DRIVAS, Dimitrios     GRE    Men   
3  1896  Athens  Aquatics   Swimming  MALOKINIS, Ioannis     GRE    Men   
4  1896  Athens  Aquatics   Swimming  CHASAPIS, Spiridon     GRE    Men   

                        Event   Medal  
0              100M Freestyle    Gold  
1              100M Freestyle  Silver  
2  100M Freestyle For Sailors  Bronze  
3  100M Freestyle For Sailors    Gold  
4  100M Freestyle For Sailors  Silver

In [7]:
df_summer["season"] = "summer" #adding a season column

In [8]:
df_summer.head()

Year    City     Sport Discipline             Athlete Country Gender  \
0  1896  Athens  Aquatics   Swimming       HAJOS, Alfred     HUN    Men   
1  1896  Athens  Aquatics   Swimming    HERSCHMANN, Otto     AUT    Men   
2  1896  Athens  Aquatics   Swimming   DRIVAS, Dimitrios     GRE    Men   
3  1896  Athens  Aquatics   Swimming  MALOKINIS, Ioannis     GRE    Men   
4  1896  Athens  Aquatics   Swimming  CHASAPIS, Spiridon     GRE    Men   

                        Event   Medal  season  
0              100M Freestyle    Gold  summer  
1              100M Freestyle  Silver  summer  
2  100M Freestyle For Sailors  Bronze  summer  
3  100M Freestyle For Sailors    Gold  summer  
4  100M Freestyle For Sailors  Silver  summer

In [9]:
df_winter = pd.read_csv("winter.csv")

In [10]:
df_winter["season"] = "winter" #adding a season column

In [11]:
df_winter.head()

Year      City     Sport Discipline               Athlete Country Gender  \
0  1924  Chamonix  Biathlon   Biathlon           BERTHET, G.     FRA    Men   
1  1924  Chamonix  Biathlon   Biathlon        MANDRILLON, C.     FRA    Men   
2  1924  Chamonix  Biathlon   Biathlon   MANDRILLON, Maurice     FRA    Men   
3  1924  Chamonix  Biathlon   Biathlon       VANDELLE, André     FRA    Men   
4  1924  Chamonix  Biathlon   Biathlon  AUFDENBLATTEN, Adolf     SUI    Men   

             Event   Medal  season  
0  Military Patrol  Bronze  winter  
1  Military Patrol  Bronze  winter  
2  Military Patrol  Bronze  winter  
3  Military Patrol  Bronze  winter  
4  Military Patrol    Gold  winter

In [32]:
df_total = df_summer.append(df_winter,ignore_index=True)#Merging the two datasets, winter and summer with the season column as a new feature

In [33]:
df_total.dropna(inplace=True)

In [34]:
df_total.head()

Year    City     Sport Discipline             Athlete Country Gender  \
0  1896  Athens  Aquatics   Swimming       HAJOS, Alfred     HUN    Men   
1  1896  Athens  Aquatics   Swimming    HERSCHMANN, Otto     AUT    Men   
2  1896  Athens  Aquatics   Swimming   DRIVAS, Dimitrios     GRE    Men   
3  1896  Athens  Aquatics   Swimming  MALOKINIS, Ioannis     GRE    Men   
4  1896  Athens  Aquatics   Swimming  CHASAPIS, Spiridon     GRE    Men   

                        Event   Medal  season  
0              100M Freestyle    Gold  summer  
1              100M Freestyle  Silver  summer  
2  100M Freestyle For Sailors  Bronze  summer  
3  100M Freestyle For Sailors    Gold  summer  
4  100M Freestyle For Sailors  Silver  summer

In [84]:
df_total.describe(include="all")

Year    City     Sport Discipline          Athlete Country  \
count   36931.000000   36931     36931      36931            36931   36931   
unique           NaN      41        48         72            26494     148   
top              NaN  London  Aquatics  athletics  PHELPS, Michael     USA   
freq             NaN    3563      4170       3637               22    5238   
mean     1972.957407     NaN       NaN        NaN              NaN     NaN   
std        32.447047     NaN       NaN        NaN              NaN     NaN   
min      1896.000000     NaN       NaN        NaN              NaN     NaN   
25%      1952.000000     NaN       NaN        NaN              NaN     NaN   
50%      1980.000000     NaN       NaN        NaN              NaN     NaN   
75%      2000.000000     NaN       NaN        NaN              NaN     NaN   
max      2014.000000     NaN       NaN        NaN              NaN     NaN   

       Gender       Event  Medal  season  
count   36931       36931  36931   36931  
unique      2         733      3       2  
top       Men  Ice Hockey   Gold  summer  
freq    26688        1563  12405   31161  
mean      NaN         NaN    NaN     NaN  
std       NaN         NaN    NaN     NaN  
min       NaN         NaN    NaN     NaN  
25%       NaN         NaN    NaN     NaN  
50%       NaN         NaN    NaN     NaN  
75%       NaN         NaN    NaN     NaN  
max       NaN         NaN    NaN     NaN

In [82]:
df_total["Event"].unique()

array(['100M Freestyle', '100M Freestyle For Sailors', '1200M Freestyle',
       '400M Freestyle', '100M', '110M Hurdles', '1500M', '400M', '800M',
       'Discus Throw', 'High Jump', 'Long Jump', 'Marathon', 'Pole Vault',
       'Shot Put', 'Triple Jump', 'Individual Road Race', '100KM', '10KM',
       '12-Hour Race', '1KM Time Trial', 'Sprint Indivual',
       'Foil Individual', 'Foil, Masters', 'Sabre Individual',
       'Horizontal Bar', 'Parallel Bars', 'Pommel Horse', 'Rings',
       'Rope Climbing', 'Team, Horizontal Bar', 'Team, Parallel Bars',
       'Vault', '25M Army Pistol', '25M Rapid Fire Pistol (60 Shots)',
       '50M Pistol (60 Shots)', 'Army Rifle, 200M', 'Army Rifle, 300M',
       'Doubles', 'Singles', 'Heavyweight - One Hand Lift',
       'Heavyweight - Two Hand Lift', 'Open Event', '1500M Freestyle',
       '200M Backstroke', '200M Freestyle', '200M Obstacle Event',
       '200M Team Swimming', '4000M Freestyle', 'Underwater Swimming',
       'Water Polo', 'Au Chap

In [83]:
Event = df_total["Event"].unique()
Event.sort()
Event

array(['+ 100KG', '+ 100KG (Heavyweight)', '+ 100KG (Super Heavyweight)',
       '+ 105KG', '+ 108KG, Total (Super Heavyweight)',
       '+ 110KG, Total (Super Heavyweight)', '+ 67 KG',
       '+ 71.67KG (Heavyweight)', '+ 72KG (Heavyweight)',
       '+ 73KG (Heavyweight)', '+ 75KG', '+ 78KG', '+ 78KG (Heavyweight)',
       '+ 79.38KG (Heavyweight)', '+ 80 KG', '+ 80KG (Heavyweight)',
       '+ 81KG (Heavyweight)', '+ 82.5KG (Super Heavyweight)',
       '+ 82.5KG, One-Two Hand 3 Events (Heavyweight)',
       '+ 82.5KG, One-Two Hand 5 Events (Heavyweight)',
       '+ 82.5KG, Total (Heavyweight)', '+ 82KG (Super Heavyweight)',
       '+ 87KG (Heavyweight)', '+ 87KG (Super Heavyweight)',
       '+ 90KG, Total (Heavyweight)', '+ 91KG',
       '+ 91KG (Super Heavyweight)', '+ 93KG (Heavyweight)',
       '+ 93KG (Super Heavyweight)', '+ 95KG (Heavyweight)',
       '+ 97KG (Heavyweight)', '+ 97KG (Super Heavyweight)', '+105KG',
       '+75KG', '- 47.63KG (Flyweight)', '- 47.6KG (Light-Flyweig

In [35]:
df_total["Discipline"].unique()

array(['Swimming', 'Athletics', 'Cycling Road', 'Cycling Track',
       'Fencing', 'Artistic G.', 'Shooting', 'Tennis', 'Weightlifting',
       'Wrestling Gre-R', 'Water polo', 'Archery', 'Basque Pelota',
       'Cricket', 'Croquet', 'Jumping', 'Football', 'Golf', 'Polo',
       'Rowing', 'Rugby', 'Sailing', 'Tug of War', 'Diving', 'Boxing',
       'Lacrosse', 'Roque', 'Wrestling Free.', 'Hockey', 'Jeu de Paume',
       'Rackets', 'Figure skating', 'Water Motorspor', 'Dressage',
       'Eventing', 'Modern Pentath.', 'Vaulting', 'Ice Hockey',
       'Basketball', 'Canoe / Kayak F', 'Handball', 'Judo', 'Volleyball',
       'Canoe / Kayak S', 'Synchronized S.', 'Rhythmic G.',
       'Table Tennis', 'Badminton', 'Baseball', 'Mountain Bike',
       'Softball', 'Beach volley.', 'Trampoline', 'Taekwondo',
       'Triathlon', 'BMX', 'Marathon swimming', 'Synchronized Swimming',
       'Water Polo', 'Canoe Slalom', 'Canoe Sprint', 'Cycling BMX',
       'Gymnastics Artistic', 'Gymnastics Rhythmi

In [37]:
df_total["Discipline"] = df_total["Discipline"].str.lower()#make all instances small letter to easily manage

In [39]:
Discipline = df_total["Discipline"].unique()
Discipline.sort()
Discipline

array(['alpine skiing', 'archery', 'artistic g.', 'athletics',
       'badminton', 'baseball', 'basketball', 'basque pelota',
       'beach volley.', 'beach volleyball', 'biathlon', 'bmx',
       'bobsleigh', 'boxing', 'canoe / kayak f', 'canoe / kayak s',
       'canoe slalom', 'canoe sprint', 'cricket', 'croquet',
       'cross country skiing', 'curling', 'cycling bmx', 'cycling road',
       'cycling track', 'diving', 'dressage', 'eventing', 'fencing',
       'figure skating', 'football', 'freestyle skiing', 'golf',
       'gymnastics artistic', 'gymnastics rhythmic', 'handball', 'hockey',
       'ice hockey', 'jeu de paume', 'judo', 'jumping', 'lacrosse',
       'luge', 'marathon swimming', 'modern pentath.',
       'modern pentathlon', 'mountain bike', 'nordic combined', 'polo',
       'rackets', 'rhythmic g.', 'roque', 'rowing', 'rugby', 'sailing',
       'shooting', 'short track speed skating', 'skeleton', 'ski jumping',
       'snowboard', 'softball', 'speed skating', 'swimming

In [40]:
df_total = df_total.replace('beach volley.', 'beach volleyball')
df_total = df_total.replace('bmx', 'cycling bmx')
df_total = df_total.replace('artistic g.', 'gymnastics artistic')
df_total = df_total.replace('rhythmic g.', 'gymnastics rhythmic')
df_total = df_total.replace('modern pentath.', 'modern pentathlon')
df_total = df_total.replace('synchronized s.', 'synchronized swimming')
df_total = df_total.replace('wrestling free.', 'wrestling freestyle')
df_total = df_total.replace('wrestling gre-r', 'wrestling greco roman')

In [41]:
x=df_total.drop(["Medal"],axis=1) #separating the dependent and independent variable columns

In [42]:
x.isnull().sum()

Year          0
City          0
Sport         0
Discipline    0
Athlete       0
Country       0
Gender        0
Event         0
season        0
dtype: int64

In [43]:
from sklearn.preprocessing import LabelEncoder

In [44]:
lb=LabelEncoder()

In [45]:
for col in x.columns:
    x[col] = lb.fit_transform(x[col])#transforming all the categorical to numerical data

In [46]:
x

Year  City  Sport  Discipline  Athlete  Country  Gender  Event  season
0         0     3      0          57     8539       58       0     79       0
1         0     3      0          57     9245        7       0     79       0
2         0     3      0          57     5572       52       0     80       0
3         0     3      0          57    14482       52       0     80       0
4         0     3      0          57     3658       52       0     80       0
...     ...   ...    ...         ...      ...      ...     ...    ...     ...
36930    32    32     37          54    10710       47       1    654       1
36931    32    32     37          54      523      140       1    654       1
36932    32    32     37          54    14488       21       1    655       1
36933    32    32     37          54    20276       31       1    655       1
36934    32    32     37          54    23676       44       1    655       1

[36931 rows x 9 columns]

In [47]:
lb2 = LabelEncoder()

In [48]:
y_clean = lb2.fit_transform(df_total.iloc[:,-2])

In [49]:
from sklearn.model_selection import train_test_split

In [285]:
x_train,x_test,y_train,y_test = train_test_split(x,y_clean,test_size=0.2,random_state =50)

In [51]:
from sklearn.metrics import confusion_matrix # TOOLS TO CHECK ACCURACY
from sklearn import metrics

NOW LET'S TRY DIFFERENT ALGORITHMS THAT SUPPORT MULTICLASS CLASSIFICATION

# LOGISTIC REGRESSION

In [52]:
from sklearn.linear_model import LogisticRegression

In [164]:
classifier_log = LogisticRegression(random_state =0,max_iter =200)

In [165]:
classifier_log.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=200, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [166]:
y_pred_log = classifier_log.predict(x_test)

In [167]:
confusion_matrix(y_test,y_pred_log)

array([[1016, 1071,  388],
       [ 881, 1289,  366],
       [ 928, 1087,  361]], dtype=int64)

In [168]:
metrics.f1_score(y_test,y_pred_log,average="macro")

0.34036709061111114

# K NEIGHBORS CLASSIFIER

In [169]:
from sklearn.neighbors import KNeighborsClassifier

In [170]:
classifier_KNN = KNeighborsClassifier()

In [171]:
classifier_KNN.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [172]:
y_pred_KNN = classifier_KNN.predict(x_test)

In [173]:
confusion_matrix(y_test,y_pred_KNN)

array([[1168,  751,  556],
       [1018, 1049,  469],
       [1046,  758,  572]], dtype=int64)

True positives are the values on the diagonal

In [174]:
metrics.f1_score(y_test,y_pred_KNN,average="macro") # THE CLOSER THE F1 SCORE TO 1, THE MORE SIGNIFICANT THE MODEL

0.3697075305345992

# NAIVE BAYES CLASSIFIER

In [175]:
from sklearn.naive_bayes import GaussianNB

In [176]:
classifier_naive = GaussianNB(var_smoothing=1e-09)

In [177]:
classifier_naive.fit(x_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [178]:
y_pred_naive = classifier_naive.predict(x_test)

In [179]:
confusion_matrix(y_test,y_pred_naive)

array([[1173,  925,  377],
       [1058, 1108,  370],
       [1091,  903,  382]], dtype=int64)

In [180]:
metrics.f1_score(y_test,y_pred_naive,average="macro")

0.3425457215806438

# DECISION TREE CLASSIFIER

In [181]:
from sklearn.tree import DecisionTreeClassifier

In [182]:
classifier_dectree = DecisionTreeClassifier(criterion = "entropy",random_state =0)

In [183]:
classifier_dectree.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [184]:
y_pred_dectree = classifier_dectree.predict(x_test)

In [185]:
confusion_matrix(y_test,y_pred_dectree)

array([[1706,  374,  395],
       [ 389, 1726,  421],
       [ 383,  380, 1613]], dtype=int64)

In [186]:
metrics.f1_score(y_test,y_pred_dectree,average="macro")

0.6828190570680198

In [311]:
print(metrics.classification_report(y_test,y_pred_dectree))

              precision    recall  f1-score   support

           0       0.69      0.69      0.69      2475
           1       0.70      0.68      0.69      2536
           2       0.66      0.68      0.67      2376

   micro avg       0.68      0.68      0.68      7387
   macro avg       0.68      0.68      0.68      7387
weighted avg       0.68      0.68      0.68      7387



# RANDOM FOREST CLASSIFIER

In [187]:
from sklearn.ensemble import RandomForestClassifier

In [188]:
classifier_forest = RandomForestClassifier(criterion="entropy",max_depth=None, max_features= 'log2',min_samples_leaf= 1, min_samples_split= 2,n_estimators=500, warm_start = True)

In [295]:
classifier_forest.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='log2', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=500, n_jobs=None,
            oob_score=False, random_state=None, verbose=0, warm_start=True)

In [296]:
y_pred_forest = classifier_forest.predict(x_test)

In [297]:
random_forest_score = metrics.f1_score(y_test,y_pred_forest,average="macro")
random_forest_score

0.7030943081083395

In [192]:
confusion_matrix(y_test,y_pred_forest)

array([[1772,  319,  384],
       [ 382, 1768,  386],
       [ 347,  374, 1655]], dtype=int64)

In [312]:
print(metrics.classification_report(y_test,y_pred_forest))

              precision    recall  f1-score   support

           0       0.71      0.72      0.71      2475
           1       0.72      0.70      0.71      2536
           2       0.68      0.70      0.69      2376

   micro avg       0.70      0.70      0.70      7387
   macro avg       0.70      0.70      0.70      7387
weighted avg       0.70      0.70      0.70      7387



THIS IS ONE OF OUR TOPS, SO LET'S CHECK ACCURACY AGAIN WITH CROSS VALIDATION

In [299]:
scoring=['precision_macro','recall_macro','f1_macro']
accuracies_forest = cross_validate(classifier_forest, x_train,y_train,scoring=scoring,cv=10)

In [307]:
random_forest_validated = accuracies_forest["test_f1_macro"].mean()
random_forest_validated

0.6848057834401488

# GRADIENT BOOSTING CLASSIFIER

In [193]:
from sklearn.ensemble import GradientBoostingClassifier

In [194]:
classifier_GBC = GradientBoostingClassifier(random_state=2)
classifier_GBC.fit(x_train,y_train)
y_pred_GBC = classifier_GBC.predict(x_test)

In [195]:
metrics.f1_score(y_test,y_pred_GBC,average="macro")

0.4357335338324047

In [196]:
metrics.confusion_matrix(y_test,y_pred_GBC)

array([[1218,  674,  583],
       [ 748, 1231,  557],
       [ 862,  715,  799]], dtype=int64)

# XGB CLASSIFIER

In [89]:
from xgboost import XGBClassifier

In [197]:
classifier_XGB = XGBClassifier(random_state =3)
classifier_XGB.fit(x_train,y_train)
y_pred_XGB = classifier_XGB.predict(x_test)

[13:13:26] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


In [198]:
metrics.f1_score(y_test,y_pred_XGB,average="macro")

0.5788786837378824

In [199]:
metrics.confusion_matrix(y_test,y_pred_XGB)

array([[1452,  484,  539],
       [ 470, 1583,  483],
       [ 563,  562, 1251]], dtype=int64)

# BAGGING CLASSIFIER

In [93]:
from sklearn.ensemble import BaggingClassifier

In [286]:
classifier_BC = BaggingClassifier(n_jobs=-1,random_state =3,n_estimators=150,base_estimator = DecisionTreeClassifier(criterion="entropy",max_depth = None, min_samples_leaf= 1, min_samples_split= 2))
classifier_BC.fit(x_train,y_train)
y_pred_BC = classifier_BC.predict(x_test)

In [287]:
bagging_classifier_score =metrics.f1_score(y_test,y_pred_BC,average="macro")
bagging_classifier_score

0.7165867882724322

In [288]:
metrics.confusion_matrix(y_test,y_pred_BC)

array([[1798,  317,  360],
       [ 361, 1820,  355],
       [ 348,  351, 1677]], dtype=int64)

In [313]:
print(metrics.classification_report(y_test,y_pred_BC))

              precision    recall  f1-score   support

           0       0.72      0.73      0.72      2475
           1       0.73      0.72      0.72      2536
           2       0.70      0.71      0.70      2376

   micro avg       0.72      0.72      0.72      7387
   macro avg       0.72      0.72      0.72      7387
weighted avg       0.72      0.72      0.72      7387



THIS IS ONE OF OUR TOPS, SO LET'S CHECK ACCURACY AGAIN WITH CROSS VALIDATION

In [255]:
from sklearn.model_selection import cross_validate


In [ ]:
scoring=['precision_macro','recall_macro','f1_macro']

In [293]:
accuracies_bag = cross_validate(classifier_BC, x_train,y_train,scoring=scoring,cv=10)

In [309]:
bagging_classifier_validated = accuracies_bag["test_f1_macro"].mean()
bagging_classifier_validated

0.6972993189862835

# EXTRA TREE CLASSIFIER

In [147]:
from sklearn.tree import ExtraTreeClassifier

In [200]:
classifier_ETC = ExtraTreeClassifier(random_state =3)
classifier_ETC.fit(x_train,y_train)
y_pred_ETC = classifier_ETC.predict(x_test)

In [201]:
metrics.f1_score(y_test,y_pred_ETC,average="macro")

0.6153014735681133

In [202]:
metrics.confusion_matrix(y_test,y_pred_ETC)

array([[1488,  462,  525],
       [ 460, 1600,  476],
       [ 438,  479, 1459]], dtype=int64)

# LET'S OPTIMIZE DECISION TREE

In [116]:
from sklearn.model_selection import GridSearchCV

In [150]:
classifier_dtree_grid = DecisionTreeClassifier(criterion="entropy")

In [151]:
parameters_dtree = [{"max_depth" : [None,1,2,5,7,9],"min_samples_leaf":[1,2,4],"min_samples_split":[2,4,6,8]}]

grid_search_dtree = GridSearchCV(estimator = classifier_dtree_grid ,param_grid = parameters_dtree, n_jobs=-1,cv=10)

In [152]:
grid_search_dtree = grid_search_dtree.fit(x_train,y_train)

In [153]:
y_pred_tree_grid = grid_search_dtree.predict(x_test)

In [154]:
metrics.f1_score(y_test,y_pred_tree_grid,average="macro")

0.6841445805962563

In [155]:
grid_search_dtree.best_params_

{'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 2}

NOW LET'S IMPLEMENT IN THE MODEL

In [314]:
classifier_dtree_grid_best = DecisionTreeClassifier(criterion='entropy',max_depth = None, min_samples_leaf= 1, min_samples_split= 2)

In [315]:
classifier_dtree_grid_best.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [316]:
y_pred_tree_grid_best = classifier_dtree_grid_best.predict(x_test)

In [317]:
decision_tree_score = metrics.f1_score(y_test,y_pred_tree_grid_best,average="macro")
decision_tree_score

0.6829187303569242

In [328]:
print(metrics.classification_report(y_test,y_pred_tree_grid_best))

              precision    recall  f1-score   support

           0       0.69      0.69      0.69      2475
           1       0.70      0.68      0.69      2536
           2       0.66      0.68      0.67      2376

   micro avg       0.68      0.68      0.68      7387
   macro avg       0.68      0.68      0.68      7387
weighted avg       0.68      0.68      0.68      7387



THIS IS ONE OF OUR TOPS, SO LET'S CHECK ACCURACY AGAIN WITH CROSS VALIDATION

In [319]:
scoring=['precision_macro','recall_macro','f1_macro']

In [320]:
accuracies_dtree = cross_validate(classifier_dtree_grid_best, x_train,y_train,scoring=scoring,cv=10)

In [321]:
decision_tree_validated=accuracies_dtree["test_f1_macro"].mean()
decision_tree_validated

0.6711423513366203

# SO FAR...OUR BEST MODELS WERE DERIVED WITH RANDOM FOREST, DECISION TREE AND BAGGING CLASSIFIER 

# WITHOUT CROSS VALIDATION

In [325]:
classifier_df = pd.DataFrame(data = np.array([bagging_classifier_score,random_forest_score,decision_tree_score]),columns = ["F1-Scores(Macro)"],index=["Bagging Classifier","Random_Forest","Decision Tree"])

In [326]:
classifier_df

F1-Scores(Macro)
Bagging Classifier          0.716587
Random_Forest               0.703094
Decision Tree               0.682919

# WITH CROSS VALIDATION

In [327]:
classifier_df_validated = pd.DataFrame(data = np.array([bagging_classifier_validated,random_forest_validated,decision_tree_validated]),columns = ["Cross Validated F1-Scores(Macro)"],index=["Bagging Classifier","Random_Forest","Decision Tree"])
classifier_df_validated

Cross Validated F1-Scores(Macro)
Bagging Classifier                          0.697299
Random_Forest                               0.684806
Decision Tree                               0.671142